services:
  - type: web
    name: ai-ledger-solutions
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
    autoDeploy: true
    plan: starter
    region: oregon
    branch: main

  - type: web
    name: ai-ledger-dashboard
    runtime: node
    buildCommand: npm install
    startCommand: node run-dashboard.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
    healthCheckPath: /api/status
    autoDeploy: true
    plan: starter
    region: oregon
    branch: main 